name: build

on:
  push:
    branches:
      - esm
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          cache: true
          install: false

      - name: Run pnpm install
        run: |
          pnpm ci
          tree node_modules/.pnpm/ | grep @rolldown+binding

      - name: Run build
        run: |
          pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist
