name: publish

run-name: Publish ${{ github.ref_name }}

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    if: github.ref_type == 'tag'
    uses: ./.github/workflows/test.yml

  release:
    needs: [test]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Create release draft
        uses: softprops/action-gh-release@v3
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          draft: true

  publish:
    needs: [release]
    runs-on: ubuntu-latest
    environment:
      name: npm-publish
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          cache: true
          install: false

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: "package.json"
          registry-url: 'https://registry.npmjs.org/'

      - name: Run pnpm install
        run: |
          pnpm ci

      - name: Run build
        run: |
          pnpm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist
          path: dist

      - name: Publish package
        run: |
          npm publish --access public
