name: test

on:
  push:
    branches:
      - esm
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ^10

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: "package.json"
          cache: 'pnpm'

      - name: Run apt install
        run: |
          sudo apt update
          sudo apt install fontforge ttfautohint

      - name: Run pnpm install
        run: |
          pnpm install

      - name: Run tests
        run: |
          pnpm run test:grunt
          pnpm run test:node:cov
