name: test

on:
  push:
    branches:
      - esm
  pull_request:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x, 22.x, 24.x, 26.x]
    steps:
      - uses: actions/checkout@v7

      - name: Setup pnpm and Node.js
        uses: pnpm/setup@v2
        with:
          runtime: node@${{ matrix.node-version }}
          cache: true
          install: false

      - name: Run apt install
        run: |
          sudo apt update
          sudo apt install fontforge ttfautohint

      - name: Run pnpm install
        run: |
          pnpm ci --no-runtime

      - name: Run tests
        if: matrix.node-version != '20.x'
        run: |
          pnpm exec node -v
          pnpm run test:grunt
          pnpm run test:node:cov

      - name: Run tests on Node.js 20.x
        if: matrix.node-version == '20.x'
        run: |
          pnpm exec node -v
          pnpm dlx tsx ./node_modules/grunt/bin/grunt clean webfont --gruntfile ./Gruntfile.ts --stack
          pnpm dlx tsx --test-only ./test/webfont.test.ts --no-clean
          pnpm dlx tsx --experimental-test-coverage --test ./test/webfont.test.ts
